---

- hosts: ab-sre-defectdojo-server-01-sea2
  become: yes
  vars_files:
    - vars/vars.yml
  tasks: 
    - include: tasks/base-packages.yml
    - include: tasks/docker-compose-install.yml
    - include: tasks/deploy-dd.yml
